const users = [
  {
    name: 'WasteWise Admin',
    email: 'admin@wastewise.org',
    password: 'password123',
    role: 'admin',
    phone: '+91 98111 00000',
    address: 'Eco Park Complex, Barakhamba Road',
    city: 'New Delhi',
    accessibilityMode: false,
    voiceSettings: {
      language: 'en-IN',
      speechToTextEnabled: true,
      textToSpeechEnabled: true,
      autoVoiceFeedback: true,
      speechRate: 1.0,
      volume: 1.0,
    },
  },
  {
    name: 'Rahul Sharma',
    email: 'user@wastewise.org',
    password: 'password123',
    role: 'user',
    phone: '+91 98765 43210',
    address: 'B-42 Green Park Extension',
    city: 'New Delhi',
    accessibilityMode: false,
    voiceSettings: {
      language: 'en-IN',
      speechToTextEnabled: true,
      textToSpeechEnabled: true,
      autoVoiceFeedback: true,
      speechRate: 1.0,
      volume: 1.0,
    },
  },
];

const recyclingServices = [
  {
    name: 'GreenScrap Doorstep Kabadiwala',
    serviceType: 'Kabadiwala / Doorstep Scrap Dealer',
    phone: '+91 98102 34567',
    email: 'delhi@greenscrap.in',
    address: 'Plot 44, Okhla Phase III Industrial Area',
    city: 'New Delhi',
    pincode: '110020',
    location: { latitude: 28.5355, longitude: 77.2732 },
    googleMapsUrl: 'https://maps.google.com/?q=28.5355,77.2732',
    spcbRegNumber: 'DPCC/EPR/2026/DL-4491',
    establishedYear: 2016,
    acceptedMaterials: ['Plastic', 'Paper', 'Metal', 'Cardboard', 'Glass', 'E-Waste'],
    ratesPerKg: [
      { material: 'PET Plastic Bottles', price: 18, unit: 'kg' },
      { material: 'Old Newspaper (Raddi)', price: 16, unit: 'kg' },
      { material: 'Corrugated Cardboard', price: 14, unit: 'kg' },
      { material: 'Iron Scrap (Loha)', price: 32, unit: 'kg' },
      { material: 'Copper Wire', price: 450, unit: 'kg' },
      { material: 'Brass (Pital)', price: 320, unit: 'kg' },
    ],
    rating: 4.9,
    reviewCount: 142,
    verified: true,
    workingHours: '08:30 AM - 07:30 PM (Daily)',
    description: 'Certified neighbourhood kabadiwala network providing digital weighing machines at your doorstep and instant UPI payments.',
    freePickupAvailable: true,
    minWeightKg: 5,
    audioOverview: 'GreenScrap Doorstep Kabadiwala operates across Delhi NCR. They accept plastic, paper, cardboard, metal, glass, and electronic scrap with verified digital weighing scales.',
  },
  {
    name: 'Swachh Bharat E-Waste Recyclers',
    serviceType: 'E-Waste Recycling Hub',
    phone: '+91 99801 76543',
    email: 'support@swachhe-waste.org',
    address: 'Electronic City Phase 1, Hosur Road',
    city: 'Bengaluru',
    pincode: '560100',
    location: { latitude: 12.8452, longitude: 77.6602 },
    googleMapsUrl: 'https://maps.google.com/?q=12.8452,77.6602',
    spcbRegNumber: 'KSPCB/E-WASTE/BLR-0982',
    establishedYear: 2019,
    acceptedMaterials: ['E-Waste', 'Metal'],
    ratesPerKg: [
      { material: 'Laptops & Motherboards', price: 120, unit: 'kg' },
      { material: 'Broken Smart Phones', price: 85, unit: 'piece' },
      { material: 'Lithium-Ion Batteries', price: 45, unit: 'kg' },
      { material: 'Copper Wires & Adapters', price: 210, unit: 'kg' },
    ],
    rating: 4.8,
    reviewCount: 98,
    verified: true,
    workingHours: '09:00 AM - 06:00 PM (Mon-Sat)',
    description: 'Pollution Control Board certified scientific E-waste recycling plant with zero-landfill toxic mineral recovery guarantees.',
    freePickupAvailable: true,
    minWeightKg: 2,
    audioOverview: 'Swachh Bharat E-Waste Recyclers provides authorized e-waste disposal in Bengaluru. They accept computers, phones, batteries, and copper cabling.',
  },
  {
    name: 'Janata Raddi & Metal Mart',
    serviceType: 'Kabadiwala / Doorstep Scrap Dealer',
    phone: '+91 98205 11223',
    email: 'mumbai@janataraddi.com',
    address: 'Near Dadar Western Railway Station',
    city: 'Mumbai',
    pincode: '400028',
    location: { latitude: 19.0178, longitude: 72.8478 },
    googleMapsUrl: 'https://maps.google.com/?q=19.0178,72.8478',
    spcbRegNumber: 'MPCB/MUM/SCRAP-5512',
    establishedYear: 1985,
    acceptedMaterials: ['Paper', 'Cardboard', 'Plastic', 'Metal'],
    ratesPerKg: [
      { material: 'Newspaper & Magazines', price: 16, unit: 'kg' },
      { material: 'Office White Paper', price: 18, unit: 'kg' },
      { material: 'Carton / Packaging Box', price: 14, unit: 'kg' },
      { material: 'Mixed Steel & Iron', price: 34, unit: 'kg' },
      { material: 'Aluminum Utensils', price: 110, unit: 'kg' },
    ],
    rating: 4.7,
    reviewCount: 210,
    verified: true,
    workingHours: '09:00 AM - 08:00 PM (Daily)',
    description: 'Trusted family scrap dealers since 1985 with transparent fair market buyback rates and instant cash settlement.',
    freePickupAvailable: true,
    minWeightKg: 10,
    audioOverview: 'Janata Raddi and Metal Mart in Mumbai collects paper, cardboard, books, plastics, and domestic metals with immediate cash or UPI payment.',
  },
  {
    name: 'Kolkata Circular Scrap Corporation',
    serviceType: 'Scrap Mart & Metal Center',
    phone: '+91 98310 99887',
    email: 'info@kolkatarecycle.co.in',
    address: 'Strand Road, Burrabazar',
    city: 'Kolkata',
    pincode: '700001',
    location: { latitude: 22.5850, longitude: 88.3500 },
    googleMapsUrl: 'https://maps.google.com/?q=22.5850,88.3500',
    spcbRegNumber: 'WBPCB/KOL/RECOVERY-881',
    establishedYear: 2012,
    acceptedMaterials: ['Metal', 'Plastic', 'Glass', 'Paper'],
    ratesPerKg: [
      { material: 'Iron / Steel Scrap', price: 31, unit: 'kg' },
      { material: 'Beer & Liquor Bottles', price: 6, unit: 'piece' },
      { material: 'PET Soft Drink Bottles', price: 17, unit: 'kg' },
      { material: 'Corrugated Paper', price: 13, unit: 'kg' },
    ],
    rating: 4.6,
    reviewCount: 76,
    verified: true,
    workingHours: '09:30 AM - 07:00 PM (Mon-Sat)',
    description: 'Bulk household and commercial waste salvage center connecting local citizens directly to circular smelting and pulping mills.',
    freePickupAvailable: true,
    minWeightKg: 8,
    audioOverview: 'Kolkata Circular Scrap Corporation in Burrabazar accepts bulk household scrap, glass containers, iron, and packaging paper.',
  },
  {
    name: 'Punjab GreenTech Scrap Recovery',
    serviceType: 'Kabadiwala / Doorstep Scrap Dealer',
    phone: '+91 98888 12345',
    email: 'contact@punjabgreentech.org',
    address: 'Focal Point Industrial Zone, Sherpur',
    city: 'Ludhiana',
    pincode: '141010',
    location: { latitude: 30.9010, longitude: 75.8573 },
    googleMapsUrl: 'https://maps.google.com/?q=30.9010,75.8573',
    spcbRegNumber: 'PPCB/LDH/IND-SCRAP-410',
    establishedYear: 2017,
    acceptedMaterials: ['Metal', 'Plastic', 'Cardboard', 'E-Waste'],
    ratesPerKg: [
      { material: 'Machinery Iron Scrap', price: 35, unit: 'kg' },
      { material: 'Brass / Bronze', price: 330, unit: 'kg' },
      { material: 'Hard Plastic Buckets', price: 22, unit: 'kg' },
      { material: 'Cardboard Cartons', price: 15, unit: 'kg' },
    ],
    rating: 4.9,
    reviewCount: 115,
    verified: true,
    workingHours: '08:00 AM - 07:00 PM (Mon-Sat)',
    description: 'Reliable doorstep scrap collection with heavy-duty vehicles for both household scrap and SME manufacturing off-cuts.',
    freePickupAvailable: true,
    minWeightKg: 10,
    audioOverview: 'Punjab GreenTech Scrap Recovery in Ludhiana specializes in metal recycling, plastic containers, and industrial packaging paper.',
  },
  {
    name: 'Deccan CleanCity Compost & Recyclers',
    serviceType: 'Municipal Dry Waste Center',
    phone: '+91 94401 23456',
    email: 'info@deccanclean.org',
    address: 'Kukatpally Housing Board Colony',
    city: 'Hyderabad',
    pincode: '500072',
    location: { latitude: 17.4875, longitude: 78.3953 },
    googleMapsUrl: 'https://maps.google.com/?q=17.4875,78.3953',
    spcbRegNumber: 'TSPCB/HYD/DRYWASTE-102',
    establishedYear: 2020,
    acceptedMaterials: ['Plastic', 'Paper', 'Glass', 'Organic'],
    ratesPerKg: [
      { material: 'Mixed Dry Plastics', price: 16, unit: 'kg' },
      { material: 'Carton Waste', price: 14, unit: 'kg' },
      { material: 'Glass Jars', price: 5, unit: 'kg' },
    ],
    rating: 4.8,
    reviewCount: 88,
    verified: true,
    workingHours: '07:30 AM - 05:30 PM (Daily)',
    description: 'Community-led material recovery facility facilitating both zero-waste composting and doorstep recyclables aggregation.',
    freePickupAvailable: false,
    minWeightKg: 5,
    audioOverview: 'Deccan CleanCity Center in Hyderabad manages decentralized waste segregation, organic compost units, and municipal recyclables.',
  },
  {
    name: 'Pune GreenCircle Circular Hub',
    serviceType: 'Kabadiwala / Doorstep Scrap Dealer',
    phone: '+91 98901 22334',
    email: 'pune@greencircle.org',
    address: 'Bhosari MIDC Industrial Area, Pimpri-Chinchwad',
    city: 'Pune',
    pincode: '411026',
    location: { latitude: 18.6298, longitude: 73.8131 },
    googleMapsUrl: 'https://maps.google.com/?q=18.6298,73.8131',
    spcbRegNumber: 'MPCB/PUN/EPR-6619',
    establishedYear: 2018,
    acceptedMaterials: ['Plastic', 'Paper', 'Metal', 'E-Waste'],
    ratesPerKg: [
      { material: 'PET Bottles', price: 19, unit: 'kg' },
      { material: 'Industrial Steel Scrap', price: 34, unit: 'kg' },
      { material: 'Cardboard Cartons', price: 15, unit: 'kg' },
      { material: 'Copper Motors', price: 440, unit: 'kg' },
    ],
    rating: 4.9,
    reviewCount: 164,
    verified: true,
    workingHours: '08:30 AM - 07:00 PM (Mon-Sat)',
    description: 'MIDC recognized formal scrap aggregation hub with high precision certified weighbridges and on-spot UPI settlement.',
    freePickupAvailable: true,
    minWeightKg: 5,
    audioOverview: 'Pune GreenCircle operates in Bhosari MIDC and Pimpri Chinchwad. They collect plastics, packaging paper, industrial metals, and electrical scrap.',
  },
  {
    name: 'Chennai EcoRecover Material Facility',
    serviceType: 'Municipal Dry Waste Center',
    phone: '+91 94440 88776',
    email: 'chennai@ecorecover.in',
    address: 'Ambattur Industrial Estate 3rd Phase',
    city: 'Chennai',
    pincode: '600058',
    location: { latitude: 13.1143, longitude: 80.1548 },
    googleMapsUrl: 'https://maps.google.com/?q=13.1143,80.1548',
    spcbRegNumber: 'TNPCB/CHN/MAT-REC-3301',
    establishedYear: 2021,
    acceptedMaterials: ['Plastic', 'Paper', 'Metal', 'Glass', 'E-Waste'],
    ratesPerKg: [
      { material: 'PET Plastic Containers', price: 18, unit: 'kg' },
      { material: 'Waste White Paper', price: 17, unit: 'kg' },
      { material: 'Aluminum Extrusions', price: 115, unit: 'kg' },
      { material: 'Beer Glass Bottles', price: 6, unit: 'piece' },
    ],
    rating: 4.7,
    reviewCount: 92,
    verified: true,
    workingHours: '09:00 AM - 06:30 PM (Daily)',
    description: 'GCC affiliated automated material recovery facility channelizing segregated recyclables to accredited recycling mills.',
    freePickupAvailable: true,
    minWeightKg: 8,
    audioOverview: 'Chennai EcoRecover in Ambattur accepts sorted dry waste, plastics, glass containers, and metals with full digital traceability.',
  },
];

// 25 classified items: 15 recyclable, 5 organic, 3 e-waste, 2 hazardous
const classifications = [
  // 15 Recyclable items (Plastic, Paper, Metal, Glass)
  {
    title: 'Bisleri 1L Mineral Water Bottle',
    category: 'Recyclable',
    confidence: 96,
    material: 'Clear PET (Polyethylene Terephthalate #1)',
    disposalInstructions: 'Place the bottle in a dry recyclable waste collection container.',
    preparation: 'Empty liquid residue and rinse cleanly. Crush to save storage space.',
    environmentalImpact: 'Prevents petroleum consumption and saves 0.12 kg of carbon emissions.',
    ecoPoints: 15,
    co2SavedKg: 0.12,
    binColor: 'Blue (Dry Recyclable)',
    notes: 'Office meeting batch',
    imageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Bisleri Mineral Water Bottle. Category: Recyclable. Confidence: 96 percent. Material: PET plastic. Disposal method: Place in dry recyclable container. Preparation: Empty and rinse cleanly.',
  },
  {
    title: 'Amazon Corrugated Shipping Box',
    category: 'Paper',
    confidence: 97,
    material: 'Double-walled Kraft Paper Cardboard',
    disposalInstructions: 'Flatten and place with dry paper recyclables or give to local Kabadiwala.',
    preparation: 'Remove plastic adhesive shipping tapes and address stickers.',
    environmentalImpact: 'Cardboard recycling saves 17 trees and 4000 kWh of electrical energy per ton.',
    ecoPoints: 20,
    co2SavedKg: 0.28,
    binColor: 'Blue (Dry Paper)',
    notes: 'Online shopping delivery package',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Corrugated Shipping Box. Category: Paper and Cardboard. Confidence: 97 percent. Material: Kraft paper. Disposal method: Flatten and deposit into dry paper recycling bin.',
  },
  {
    title: 'Coca-Cola 300ml Aluminum Can',
    category: 'Metal',
    confidence: 95,
    material: 'Grade 3104 Aluminum Alloy',
    disposalInstructions: 'Place in metal scrap or dry recyclables. Highly valued by scrap collectors.',
    preparation: 'Rinse out sticky sugary syrup before binning. Crush flat.',
    environmentalImpact: 'Recycling aluminum consumes 95% less energy than mining raw bauxite.',
    ecoPoints: 25,
    co2SavedKg: 0.42,
    binColor: 'Blue (Dry Metal)',
    notes: 'Collected after family lunch',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Aluminum Beverage Can. Category: Metal. Confidence: 95 percent. Material: Recyclable aluminum. Disposal method: Deposit in metal scrap.',
  },
  {
    title: 'Kissan Jam Glass Jar',
    category: 'Glass',
    confidence: 93,
    material: 'Silica Soda-Lime Glass Container',
    disposalInstructions: 'Place in dry recyclable container. Glass can be recycled infinitely.',
    preparation: 'Wash clean with warm water. Remove metal screw lid separately.',
    environmentalImpact: 'Cuts glass furnace energy consumption by 20% and prevents beach sand extraction.',
    ecoPoints: 20,
    co2SavedKg: 0.22,
    binColor: 'Blue (Dry Glass)',
    notes: 'Empty kitchen container',
    imageUrl: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Glass Jam Jar. Category: Glass. Confidence: 93 percent. Material: Soda-lime glass. Disposal method: Place in glass recycling bin.',
  },
  {
    title: 'The Times of India Newspaper Stack',
    category: 'Paper',
    confidence: 99,
    material: 'Standard Virgin & Recycled Newsprint',
    disposalInstructions: 'Bundle neatly and sell to your neighbourhood kabadiwala for ₹16/kg.',
    preparation: 'Keep dry and tied with natural jute string. Avoid grease or wet stains.',
    environmentalImpact: 'Saves 3 cubic yards of landfill space per ton of recycled newspaper.',
    ecoPoints: 30,
    co2SavedKg: 0.65,
    binColor: 'Blue (Dry Paper)',
    notes: 'One month newspaper pile',
    imageUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Newspaper Stack. Category: Paper. Confidence: 99 percent. Material: Newsprint. Disposal method: Hand over to local kabadiwala.',
  },
  {
    title: 'Amul Milk Pouch 500ml',
    category: 'Recyclable',
    confidence: 91,
    material: 'Low-Density Polyethylene (LDPE #4)',
    disposalInstructions: 'Rinse thoroughly, dry, and place into soft plastic collection bag.',
    preparation: 'Snip tiny corner, rinse with water, and air dry before collection.',
    environmentalImpact: 'Keeps flexible single-use film plastics out of city storm drains.',
    ecoPoints: 10,
    co2SavedKg: 0.08,
    binColor: 'Blue (Dry Recyclable)',
    notes: 'Daily breakfast pouch',
    imageUrl: 'https://images.unsplash.com/photo-1589365278144-c9e705f843ba?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Milk Pouch. Category: Recyclable. Confidence: 91 percent. Material: LDPE plastic film. Preparation: Rinse cleanly and dry.',
  },
  {
    title: 'Dettol Handwash Plastic Dispenser Bottle',
    category: 'Recyclable',
    confidence: 94,
    material: 'High-Density Polyethylene (HDPE #2)',
    disposalInstructions: 'Place in plastic recycling bin. Unscrew pump dispenser nozzle.',
    preparation: 'Rinse interior with lukewarm water. Pump nozzle has internal metal spring.',
    environmentalImpact: 'High resale value and easily flaked into durable recycled plastic pellets.',
    ecoPoints: 15,
    co2SavedKg: 0.14,
    binColor: 'Blue (Dry Recyclable)',
    notes: 'Bathroom refill',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Handwash Bottle. Category: Recyclable. Confidence: 94 percent. Material: HDPE plastic.',
  },
  {
    title: 'A4 White Office Printer Paper',
    category: 'Paper',
    confidence: 98,
    material: 'High-grade Chemical Wood Pulp',
    disposalInstructions: 'Collect in designated office paper recycling bin.',
    preparation: 'Remove metal paperclips and plastic staples before recycling.',
    environmentalImpact: 'High pulp yield during de-inking and paper remanufacturing.',
    ecoPoints: 20,
    co2SavedKg: 0.35,
    binColor: 'Blue (Dry Paper)',
    notes: 'Old project drafts',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Office Paper. Category: Paper. Confidence: 98 percent. Material: Chemical wood pulp.',
  },
  {
    title: 'Tin Food Can (Pineapple Slices)',
    category: 'Metal',
    confidence: 93,
    material: 'Tin-plated Steel',
    disposalInstructions: 'Place in dry metals recyclables container.',
    preparation: 'Rinse out fruit syrup and push sharp metal lid inside can.',
    environmentalImpact: 'Conserves iron ore resources and prevents rust leaching.',
    ecoPoints: 20,
    co2SavedKg: 0.38,
    binColor: 'Blue (Dry Metal)',
    notes: 'Bakery kitchen scrap',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Tin Food Can. Category: Metal. Confidence: 93 percent. Material: Tin plated steel.',
  },
  {
    title: 'Olive Oil Dark Green Glass Bottle',
    category: 'Glass',
    confidence: 92,
    material: 'Colored Emerald Silica Glass',
    disposalInstructions: 'Deposit in glass recycling drop-off bin.',
    preparation: 'Drain remaining oil, wash with warm detergent, remove plastic pour spout.',
    environmentalImpact: 'Reduces raw mineral extraction for glass bottle manufacturing.',
    ecoPoints: 18,
    co2SavedKg: 0.25,
    binColor: 'Blue (Dry Glass)',
    notes: 'Kitchen cooking oil',
    imageUrl: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Green Glass Bottle. Category: Glass. Confidence: 92 percent. Material: Silica glass.',
  },
  {
    title: 'Tropicana Juice Tetra Pak Carton',
    category: 'Recyclable',
    confidence: 89,
    material: 'Multi-layer Aseptic Packaging (75% Paperboard, 20% Polyethylene, 5% Aluminum)',
    disposalInstructions: 'Deposit in dry recyclables for specialized hydrapulping separation.',
    preparation: 'Flatten carton and push plastic straw inside if attached.',
    environmentalImpact: 'Paper fibers extracted for industrial stationery; polymers used for roofing tiles.',
    ecoPoints: 15,
    co2SavedKg: 0.16,
    binColor: 'Blue (Dry Recyclable)',
    notes: 'Breakfast juice box',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Tetra Pak Carton. Category: Recyclable. Confidence: 89 percent. Material: Multi layer aseptic carton.',
  },
  {
    title: 'Plastic Shampoo Container',
    category: 'Recyclable',
    confidence: 95,
    material: 'Polypropylene (PP #5)',
    disposalInstructions: 'Empty and place in household plastics bin.',
    preparation: 'Rinse with water until soapy bubbles clear. Replace screw cap.',
    environmentalImpact: 'Re-molded into plastic pallets, buckets, and automotive components.',
    ecoPoints: 15,
    co2SavedKg: 0.18,
    binColor: 'Blue (Dry Recyclable)',
    notes: 'Household personal care item',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Shampoo Bottle. Category: Recyclable. Confidence: 95 percent. Material: Polypropylene plastic.',
  },
  {
    title: 'Steel Kitchen Utensil (Old Kadhai Handle)',
    category: 'Metal',
    confidence: 96,
    material: 'Stainless Steel Scrap (SS 304)',
    disposalInstructions: 'Hand over to metal kabadiwala for premium scrap rate.',
    preparation: 'Clean off grease. Separate any plastic or bakelite grip fasteners.',
    environmentalImpact: 'Recycled stainless steel retains 100% mechanical strength in foundry re-melting.',
    ecoPoints: 30,
    co2SavedKg: 0.72,
    binColor: 'Blue (Dry Metal)',
    notes: 'Kitchen renovation scrap',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Steel Scrap. Category: Metal. Confidence: 96 percent. Material: Stainless steel.',
  },
  {
    title: 'Brown Kraft Paper Grocery Bag',
    category: 'Paper',
    confidence: 97,
    material: '100% Unbleached Virgin Kraft Paper',
    disposalInstructions: 'Recycle with dry paper or shred for garden compost brown matter.',
    preparation: 'Keep dry. Remove any plastic nylon cord handles.',
    environmentalImpact: 'Biodegrades naturally in weeks or recycled into cardboard packaging.',
    ecoPoints: 15,
    co2SavedKg: 0.12,
    binColor: 'Blue (Dry Paper)',
    notes: 'Supermarket shopping bag',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Kraft Paper Bag. Category: Paper. Confidence: 97 percent. Material: Kraft paper.',
  },
  {
    title: 'Plastic Curd Container (Dahi Cup)',
    category: 'Recyclable',
    confidence: 92,
    material: 'Polypropylene (PP #5)',
    disposalInstructions: 'Wash out curd residue and stack in plastic bin.',
    preparation: 'Remove aluminum foil peel-off lid completely.',
    environmentalImpact: 'Prevents foul odour in recycling bins and facilitates clean melt processing.',
    ecoPoints: 10,
    co2SavedKg: 0.09,
    binColor: 'Blue (Dry Recyclable)',
    notes: 'Lunch dairy container',
    imageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Plastic Curd Cup. Category: Recyclable. Confidence: 92 percent. Material: Polypropylene.',
  },

  // 5 Organic items
  {
    title: 'Ripe Banana Peels & Fruit Scraps',
    category: 'Organic',
    confidence: 98,
    material: 'Biodegradable Plant Biomass & Potassium',
    disposalInstructions: 'Place in Green wet waste bin or home aerated compost bin.',
    preparation: 'Remove any fruit brand stickers before adding to compost.',
    environmentalImpact: 'Prevents landfill methane emissions and converts to nutrient-rich bio-compost.',
    ecoPoints: 10,
    co2SavedKg: 0.18,
    binColor: 'Green (Wet / Compostable)',
    notes: 'Morning fruit breakfast peel',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Banana Peels. Category: Organic. Confidence: 98 percent. Material: Biodegradable biomass. Disposal method: Green compost container.',
  },
  {
    title: 'Kitchen Vegetable Trimmings (Potato, Cauliflower)',
    category: 'Organic',
    confidence: 97,
    material: 'Raw Plant Biomass & Cellulose',
    disposalInstructions: 'Deposit in municipal green organic bin.',
    preparation: 'Do not mix with plastic wrappers, plastic rubber bands, or kitchen foil.',
    environmentalImpact: 'Generates zero methane when aerobically composted.',
    ecoPoints: 10,
    co2SavedKg: 0.22,
    binColor: 'Green (Wet / Compostable)',
    notes: 'Evening dinner cooking scrap',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Vegetable Trimmings. Category: Organic. Confidence: 97 percent. Material: Plant biomass. Disposal method: Green bin.',
  },
  {
    title: 'Used Chai Tea Leaves (Used Tea Powder)',
    category: 'Organic',
    confidence: 99,
    material: 'Nitrogen-rich Organic Tea Biomass',
    disposalInstructions: 'Rinse milk away and sprinkle around rose bushes or garden plants.',
    preparation: 'Rinse ginger and sugar crystals, excellent natural plant fertilizer.',
    environmentalImpact: 'Enriches soil micro-organisms and retains root moisture.',
    ecoPoints: 10,
    co2SavedKg: 0.15,
    binColor: 'Green (Wet / Compostable)',
    notes: 'Morning chai leftovers',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Used Tea Leaves. Category: Organic. Confidence: 99 percent. Material: Organic nitrogen biomass.',
  },
  {
    title: 'Egg Shells (Crushed Calcium Scraps)',
    category: 'Organic',
    confidence: 96,
    material: 'Calcium Carbonate Biomass',
    disposalInstructions: 'Crush finely and incorporate into garden composting pile.',
    preparation: 'Rinse interior membrane to avoid flies and crush with mortar.',
    environmentalImpact: 'Adds vital calcium to organic agricultural potting soil.',
    ecoPoints: 10,
    co2SavedKg: 0.12,
    binColor: 'Green (Wet / Compostable)',
    notes: 'Sunday breakfast shells',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Egg Shells. Category: Organic. Confidence: 96 percent. Material: Calcium carbonate biomass.',
  },
  {
    title: 'Dry Garden Autumn Leaves',
    category: 'Organic',
    confidence: 98,
    material: 'Carbon-rich Plant Foliage',
    disposalInstructions: 'Never burn! Layer with green wet kitchen waste for balanced compost.',
    preparation: 'Keep dry in a garden bag as compost bedding.',
    environmentalImpact: 'Eliminates open leaf burning smog and air pollution.',
    ecoPoints: 15,
    co2SavedKg: 0.35,
    binColor: 'Green (Wet / Compostable)',
    notes: 'Balcony garden sweeping',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Dry Garden Leaves. Category: Organic. Confidence: 98 percent. Material: Carbon plant foliage.',
  },

  // 3 E-Waste items
  {
    title: 'Discarded Android Smartphone & Lithium Battery',
    category: 'E-Waste',
    confidence: 95,
    material: 'Lithium Cobalt Oxide, Copper PCB, Gold Pins, Aluminum Chassis',
    disposalInstructions: 'Drop off at certified E-waste recycler or request an authorized pickup.',
    preparation: 'Factory reset storage, remove SIM tray, tape battery contact pads.',
    environmentalImpact: 'Recovers rare critical minerals and prevents toxic lithium soil contamination.',
    ecoPoints: 50,
    co2SavedKg: 1.45,
    binColor: 'Red / Black (Hazardous E-Waste)',
    notes: 'Old broken smartphone from drawer',
    imageUrl: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Discarded Smartphone. Category: E-Waste. Confidence: 95 percent. Material: Lithium battery and electronic circuit.',
  },
  {
    title: 'Frayed Laptop Power Charger & Adapter Cable',
    category: 'E-Waste',
    confidence: 94,
    material: 'High-purity Copper Core, PVC Sheathing, Ferrite Core, Transformer',
    disposalInstructions: 'Place in designated electronics recycling bin or give to kabadiwala.',
    preparation: 'Do not plug into wall power. Coil cable neatly.',
    environmentalImpact: 'High-grade copper is 100% recyclable with minimal refining energy.',
    ecoPoints: 35,
    co2SavedKg: 0.88,
    binColor: 'Red / Black (Hazardous E-Waste)',
    notes: 'Burned out charger cord',
    imageUrl: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Laptop Power Adapter. Category: E-Waste. Confidence: 94 percent. Material: Copper wire and transformer.',
  },
  {
    title: 'Dead AA Alkaline Batteries (Pack of 4)',
    category: 'E-Waste',
    confidence: 92,
    material: 'Zinc-Manganese Dioxide & Potassium Hydroxide',
    disposalInstructions: 'Deposit at household hazardous e-waste kiosk. Do not place in regular trash.',
    preparation: 'Place inside a sealed ziplock bag to contain any electrolyte leakage.',
    environmentalImpact: 'Prevents heavy corrosive metals from entering municipal landfill leachate.',
    ecoPoints: 30,
    co2SavedKg: 0.45,
    binColor: 'Red / Black (Hazardous E-Waste)',
    notes: 'TV remote dead batteries',
    imageUrl: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Dead Alkaline Batteries. Category: E-Waste. Confidence: 92 percent. Material: Zinc manganese dioxide.',
  },

  // 2 Hazardous items
  {
    title: 'Expired Paracetamol Medicine Blister Pack',
    category: 'Hazardous',
    confidence: 93,
    material: 'Aluminum Push-through Foil & PVC Plastic Blister',
    disposalInstructions: 'Deposit at authorized pharmacy drug take-back bin or biomedical drop-off.',
    preparation: 'Keep tablets in blister packaging. Never flush down toilet or sink.',
    environmentalImpact: 'Protects drinking water supply from active pharmaceutical chemical contamination.',
    ecoPoints: 20,
    co2SavedKg: 0.15,
    binColor: 'Yellow / Red (Biomedical & Hazardous)',
    notes: 'Expired medicine from medical box',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Expired Medicine Blister. Category: Hazardous Waste. Confidence: 93 percent. Material: Aluminum PVC composite.',
  },
  {
    title: 'Empty Aerosol Disinfectant Spray Can',
    category: 'Hazardous',
    confidence: 90,
    material: 'Pressurized Steel Aerosol Can & Hydrocarbon Propellant',
    disposalInstructions: 'Deposit at municipal chemical waste collection point. Do not puncture or incinerate.',
    preparation: 'Depress nozzle until completely depressurized and empty.',
    environmentalImpact: 'Eliminates explosion hazards in high-temperature municipal compactors.',
    ecoPoints: 20,
    co2SavedKg: 0.25,
    binColor: 'Yellow / Red (Hazardous Waste)',
    notes: 'Disinfectant spray can',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    audioExplanation: 'Waste identified: Aerosol Spray Can. Category: Hazardous. Confidence: 90 percent. Material: Pressurized steel container.',
  },
];

const pickupRequests = [
  {
    userName: 'Rahul Sharma',
    phone: '+91 98765 43210',
    address: 'B-42 Green Park Extension',
    city: 'New Delhi',
    pincode: '110016',
    wasteType: 'Plastic',
    estimatedWeight: 5,
    preferredDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    timeSlot: 'Morning (10:00 AM - 01:00 PM)',
    status: 'Scheduled',
    notes: 'Voice scheduled: 5 kilograms of plastic bottles and containers',
    assignedServiceName: 'GreenScrap Doorstep Kabadiwala',
  },
  {
    userName: 'Rahul Sharma',
    phone: '+91 98765 43210',
    address: 'B-42 Green Park Extension',
    city: 'New Delhi',
    pincode: '110016',
    wasteType: 'Paper / Cardboard',
    estimatedWeight: 12,
    preferredDate: new Date(Date.now() - 172800000).toISOString().split('T')[0],
    timeSlot: 'Afternoon (02:00 PM - 05:00 PM)',
    status: 'Completed',
    notes: 'Old newspapers stack and Amazon boxes',
    assignedServiceName: 'GreenScrap Doorstep Kabadiwala',
  },
  {
    userName: 'Priya Patel',
    phone: '+91 99000 88776',
    address: 'Flat 302, Palm Meadows, Whitefield',
    city: 'Bengaluru',
    pincode: '560066',
    wasteType: 'E-Waste',
    estimatedWeight: 3.5,
    preferredDate: new Date(Date.now() + 172800000).toISOString().split('T')[0],
    timeSlot: 'Evening (05:00 PM - 08:00 PM)',
    status: 'Pending',
    notes: 'Dead laptop batteries and copper chargers',
    assignedServiceName: 'Swachh Bharat E-Waste Recyclers',
  },
];

module.exports = {
  users,
  recyclingServices,
  classifications,
  pickupRequests,
};
